// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqfadzcuckorbhtjbxoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZmFkemN1Y2tvcmJodGpieG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxOTgyMzMsImV4cCI6MjA5MDc3NDIzM30.nok94BIKvDpRA9fKVkP3Xe7kgthcF34QBK4_h2oT_ew";

/**
 * Supabase client with proper auth refresh.
 *
 * Key settings:
 * - autoRefreshToken: true → automatically refreshes JWT before expiry
 * - persistSession: true → stores session in localStorage so it survives reload
 * - detectSessionInUrl: true → handles auth callbacks
 *
 * NOTE: We use the default LockManager (no custom `lock` override).
 * The previous no-op lock was causing token refresh failures because
 * concurrent refresh attempts had no synchronization → race conditions →
 * 401 errors after JWT expired → spinner stuck because all queries fail.
 *
 * UPDATE: Web Locks API default LockManager was causing orphaned locks
 * after 5+ minutes of usage, blocking all auth operations and freezing
 * the entire app. We now use a custom in-memory lock with explicit
 * timeout that auto-releases on error or after maxWaitMs.
 * Verified by DevTools test: Lock warning + UI freeze while raw fetch worked.
 */

// Custom in-memory lock that prevents orphaned locks.
// Each lock name has its own queue. If lock is held longer than acquireTimeout,
// the new acquirer will proceed anyway (preventing permanent deadlock).
const lockQueues = new Map<string, Promise<unknown>>();

const inMemoryLock = async <R>(
  name: string,
  acquireTimeout: number,
  fn: () => Promise<R>
): Promise<R> => {
  const previousOperation = lockQueues.get(name) ?? Promise.resolve();

  // Wait for previous operation to finish, but with timeout
  const timeoutPromise = new Promise<void>((resolve) =>
    setTimeout(resolve, acquireTimeout > 0 ? acquireTimeout : 10000)
  );

  await Promise.race([previousOperation.catch(() => undefined), timeoutPromise]);

  // Run our operation, store its promise so next caller waits for us
  const ourOperation = fn();
  const trackedPromise = ourOperation.catch(() => undefined);
  lockQueues.set(name, trackedPromise);

  // Auto-cleanup: remove from queue when done so memory doesn't grow
  trackedPromise.finally(() => {
    if (lockQueues.get(name) === trackedPromise) {
      lockQueues.delete(name);
    }
  });

  return ourOperation;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    lock: inMemoryLock,
  }
});
